// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdplnaulnxevymvwbzpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkcGxuYXVsbnhldnltdndienB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTQ2MDIsImV4cCI6MjA3Mzg3MDYwMn0.sTOS0084LRzY2e_QsJRBQDwjy9DL-8mGOpMuRApK198";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});